version: 2
updates:
- package-ecosystem: github-actions
  directory: .github/workflows
  schedule:
    interval: daily
    time: "10:00"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
